GET http://localhost:4000/jadwal

###
GET http://localhost:4000/jadwal/1

###
POST http://localhost:4000/jadwal
Content-Type: application/json

{
    "kelas": "TI.20.A.1",
    "hari": "Senin",
    "waktu": "13.00 - 15.00",
    "dosen": "Wahyu Hadikristanto, S.Kom., M.Kom.",
    "asisten1": "Maulana Hasan",
    "asisten2": "veno"
}

###
PATCH http://localhost:4000/jadwal/1
Content-Type: application/json

{
    "kelas": "TI.20.A.1",
    "hari": "Senin",
    "waktu": "13.00 - 15.00",
    "dosen": "Wahyu Hadikristanto, S.Kom., M.Kom.",
    "asisten1": "Maulana Hasan",
    "asisten2": "veno"
}

###
DELETE http://localhost:4000/jadwal/2